# Generated by Django 4.2.5 on 2025-05-07 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_image1_project_image2_project_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='image3',
        ),
    ]
